SPOOL OFF
SET LINESIZE 1000
SET TRIMOUT ON
SET FEEDBACK OFF
Set feed off
Set head off

SPOOL backup.sh

SELECT 'cp ' || NAME || ' /bkp' FROM V$CONTROLFILE
UNION
SELECT 'cp ' || NAME || ' /bkp' FROM V$TEMPFILE
UNION
SELECT 'cp ' || NAME || ' /bkp' FROM V$DBFILE
UNION
SELECT 'cp ' || MEMBER || ' /bkp' FROM V$LOGFILE;

SPOOL OFF

SHUTDOWN IMMEDIATE

EXIT
